# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dkim/aaa

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dkim/aaa

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dkim/aaa/CMakeFiles /Users/dkim/aaa/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dkim/aaa/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lastal

# Build rule for target.
lastal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lastal
.PHONY : lastal

# fast build rule for target.
lastal/fast:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/build
.PHONY : lastal/fast

#=============================================================================
# Target rules for targets named lastdb

# Build rule for target.
lastdb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lastdb
.PHONY : lastdb

# fast build rule for target.
lastdb/fast:
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/build
.PHONY : lastdb/fast

Alignment.o: Alignment.cc.o
.PHONY : Alignment.o

# target to build an object file
Alignment.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/Alignment.cc.o
.PHONY : Alignment.cc.o

Alignment.i: Alignment.cc.i
.PHONY : Alignment.i

# target to preprocess a source file
Alignment.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/Alignment.cc.i
.PHONY : Alignment.cc.i

Alignment.s: Alignment.cc.s
.PHONY : Alignment.s

# target to generate assembly for a file
Alignment.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/Alignment.cc.s
.PHONY : Alignment.cc.s

AlignmentPot.o: AlignmentPot.cc.o
.PHONY : AlignmentPot.o

# target to build an object file
AlignmentPot.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/AlignmentPot.cc.o
.PHONY : AlignmentPot.cc.o

AlignmentPot.i: AlignmentPot.cc.i
.PHONY : AlignmentPot.i

# target to preprocess a source file
AlignmentPot.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/AlignmentPot.cc.i
.PHONY : AlignmentPot.cc.i

AlignmentPot.s: AlignmentPot.cc.s
.PHONY : AlignmentPot.s

# target to generate assembly for a file
AlignmentPot.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/AlignmentPot.cc.s
.PHONY : AlignmentPot.cc.s

AlignmentWrite.o: AlignmentWrite.cc.o
.PHONY : AlignmentWrite.o

# target to build an object file
AlignmentWrite.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/AlignmentWrite.cc.o
.PHONY : AlignmentWrite.cc.o

AlignmentWrite.i: AlignmentWrite.cc.i
.PHONY : AlignmentWrite.i

# target to preprocess a source file
AlignmentWrite.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/AlignmentWrite.cc.i
.PHONY : AlignmentWrite.cc.i

AlignmentWrite.s: AlignmentWrite.cc.s
.PHONY : AlignmentWrite.s

# target to generate assembly for a file
AlignmentWrite.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/AlignmentWrite.cc.s
.PHONY : AlignmentWrite.cc.s

Alphabet.o: Alphabet.cc.o
.PHONY : Alphabet.o

# target to build an object file
Alphabet.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/Alphabet.cc.o
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/Alphabet.cc.o
.PHONY : Alphabet.cc.o

Alphabet.i: Alphabet.cc.i
.PHONY : Alphabet.i

# target to preprocess a source file
Alphabet.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/Alphabet.cc.i
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/Alphabet.cc.i
.PHONY : Alphabet.cc.i

Alphabet.s: Alphabet.cc.s
.PHONY : Alphabet.s

# target to generate assembly for a file
Alphabet.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/Alphabet.cc.s
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/Alphabet.cc.s
.PHONY : Alphabet.cc.s

Centroid.o: Centroid.cc.o
.PHONY : Centroid.o

# target to build an object file
Centroid.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/Centroid.cc.o
.PHONY : Centroid.cc.o

Centroid.i: Centroid.cc.i
.PHONY : Centroid.i

# target to preprocess a source file
Centroid.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/Centroid.cc.i
.PHONY : Centroid.cc.i

Centroid.s: Centroid.cc.s
.PHONY : Centroid.s

# target to generate assembly for a file
Centroid.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/Centroid.cc.s
.PHONY : Centroid.cc.s

CyclicSubsetSeed.o: CyclicSubsetSeed.cc.o
.PHONY : CyclicSubsetSeed.o

# target to build an object file
CyclicSubsetSeed.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/CyclicSubsetSeed.cc.o
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/CyclicSubsetSeed.cc.o
.PHONY : CyclicSubsetSeed.cc.o

CyclicSubsetSeed.i: CyclicSubsetSeed.cc.i
.PHONY : CyclicSubsetSeed.i

# target to preprocess a source file
CyclicSubsetSeed.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/CyclicSubsetSeed.cc.i
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/CyclicSubsetSeed.cc.i
.PHONY : CyclicSubsetSeed.cc.i

CyclicSubsetSeed.s: CyclicSubsetSeed.cc.s
.PHONY : CyclicSubsetSeed.s

# target to generate assembly for a file
CyclicSubsetSeed.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/CyclicSubsetSeed.cc.s
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/CyclicSubsetSeed.cc.s
.PHONY : CyclicSubsetSeed.cc.s

DiagonalTable.o: DiagonalTable.cc.o
.PHONY : DiagonalTable.o

# target to build an object file
DiagonalTable.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/DiagonalTable.cc.o
.PHONY : DiagonalTable.cc.o

DiagonalTable.i: DiagonalTable.cc.i
.PHONY : DiagonalTable.i

# target to preprocess a source file
DiagonalTable.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/DiagonalTable.cc.i
.PHONY : DiagonalTable.cc.i

DiagonalTable.s: DiagonalTable.cc.s
.PHONY : DiagonalTable.s

# target to generate assembly for a file
DiagonalTable.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/DiagonalTable.cc.s
.PHONY : DiagonalTable.cc.s

GappedXdropAligner.o: GappedXdropAligner.cc.o
.PHONY : GappedXdropAligner.o

# target to build an object file
GappedXdropAligner.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/GappedXdropAligner.cc.o
.PHONY : GappedXdropAligner.cc.o

GappedXdropAligner.i: GappedXdropAligner.cc.i
.PHONY : GappedXdropAligner.i

# target to preprocess a source file
GappedXdropAligner.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/GappedXdropAligner.cc.i
.PHONY : GappedXdropAligner.cc.i

GappedXdropAligner.s: GappedXdropAligner.cc.s
.PHONY : GappedXdropAligner.s

# target to generate assembly for a file
GappedXdropAligner.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/GappedXdropAligner.cc.s
.PHONY : GappedXdropAligner.cc.s

GappedXdropAligner2qual.o: GappedXdropAligner2qual.cc.o
.PHONY : GappedXdropAligner2qual.o

# target to build an object file
GappedXdropAligner2qual.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/GappedXdropAligner2qual.cc.o
.PHONY : GappedXdropAligner2qual.cc.o

GappedXdropAligner2qual.i: GappedXdropAligner2qual.cc.i
.PHONY : GappedXdropAligner2qual.i

# target to preprocess a source file
GappedXdropAligner2qual.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/GappedXdropAligner2qual.cc.i
.PHONY : GappedXdropAligner2qual.cc.i

GappedXdropAligner2qual.s: GappedXdropAligner2qual.cc.s
.PHONY : GappedXdropAligner2qual.s

# target to generate assembly for a file
GappedXdropAligner2qual.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/GappedXdropAligner2qual.cc.s
.PHONY : GappedXdropAligner2qual.cc.s

GappedXdropAligner3frame.o: GappedXdropAligner3frame.cc.o
.PHONY : GappedXdropAligner3frame.o

# target to build an object file
GappedXdropAligner3frame.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/GappedXdropAligner3frame.cc.o
.PHONY : GappedXdropAligner3frame.cc.o

GappedXdropAligner3frame.i: GappedXdropAligner3frame.cc.i
.PHONY : GappedXdropAligner3frame.i

# target to preprocess a source file
GappedXdropAligner3frame.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/GappedXdropAligner3frame.cc.i
.PHONY : GappedXdropAligner3frame.cc.i

GappedXdropAligner3frame.s: GappedXdropAligner3frame.cc.s
.PHONY : GappedXdropAligner3frame.s

# target to generate assembly for a file
GappedXdropAligner3frame.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/GappedXdropAligner3frame.cc.s
.PHONY : GappedXdropAligner3frame.cc.s

GappedXdropAlignerPssm.o: GappedXdropAlignerPssm.cc.o
.PHONY : GappedXdropAlignerPssm.o

# target to build an object file
GappedXdropAlignerPssm.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/GappedXdropAlignerPssm.cc.o
.PHONY : GappedXdropAlignerPssm.cc.o

GappedXdropAlignerPssm.i: GappedXdropAlignerPssm.cc.i
.PHONY : GappedXdropAlignerPssm.i

# target to preprocess a source file
GappedXdropAlignerPssm.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/GappedXdropAlignerPssm.cc.i
.PHONY : GappedXdropAlignerPssm.cc.i

GappedXdropAlignerPssm.s: GappedXdropAlignerPssm.cc.s
.PHONY : GappedXdropAlignerPssm.s

# target to generate assembly for a file
GappedXdropAlignerPssm.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/GappedXdropAlignerPssm.cc.s
.PHONY : GappedXdropAlignerPssm.cc.s

GeneralizedAffineGapCosts.o: GeneralizedAffineGapCosts.cc.o
.PHONY : GeneralizedAffineGapCosts.o

# target to build an object file
GeneralizedAffineGapCosts.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/GeneralizedAffineGapCosts.cc.o
.PHONY : GeneralizedAffineGapCosts.cc.o

GeneralizedAffineGapCosts.i: GeneralizedAffineGapCosts.cc.i
.PHONY : GeneralizedAffineGapCosts.i

# target to preprocess a source file
GeneralizedAffineGapCosts.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/GeneralizedAffineGapCosts.cc.i
.PHONY : GeneralizedAffineGapCosts.cc.i

GeneralizedAffineGapCosts.s: GeneralizedAffineGapCosts.cc.s
.PHONY : GeneralizedAffineGapCosts.s

# target to generate assembly for a file
GeneralizedAffineGapCosts.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/GeneralizedAffineGapCosts.cc.s
.PHONY : GeneralizedAffineGapCosts.cc.s

GeneticCode.o: GeneticCode.cc.o
.PHONY : GeneticCode.o

# target to build an object file
GeneticCode.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/GeneticCode.cc.o
.PHONY : GeneticCode.cc.o

GeneticCode.i: GeneticCode.cc.i
.PHONY : GeneticCode.i

# target to preprocess a source file
GeneticCode.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/GeneticCode.cc.i
.PHONY : GeneticCode.cc.i

GeneticCode.s: GeneticCode.cc.s
.PHONY : GeneticCode.s

# target to generate assembly for a file
GeneticCode.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/GeneticCode.cc.s
.PHONY : GeneticCode.cc.s

LambdaCalculator.o: LambdaCalculator.cc.o
.PHONY : LambdaCalculator.o

# target to build an object file
LambdaCalculator.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/LambdaCalculator.cc.o
.PHONY : LambdaCalculator.cc.o

LambdaCalculator.i: LambdaCalculator.cc.i
.PHONY : LambdaCalculator.i

# target to preprocess a source file
LambdaCalculator.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/LambdaCalculator.cc.i
.PHONY : LambdaCalculator.cc.i

LambdaCalculator.s: LambdaCalculator.cc.s
.PHONY : LambdaCalculator.s

# target to generate assembly for a file
LambdaCalculator.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/LambdaCalculator.cc.s
.PHONY : LambdaCalculator.cc.s

LastalArguments.o: LastalArguments.cc.o
.PHONY : LastalArguments.o

# target to build an object file
LastalArguments.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/LastalArguments.cc.o
.PHONY : LastalArguments.cc.o

LastalArguments.i: LastalArguments.cc.i
.PHONY : LastalArguments.i

# target to preprocess a source file
LastalArguments.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/LastalArguments.cc.i
.PHONY : LastalArguments.cc.i

LastalArguments.s: LastalArguments.cc.s
.PHONY : LastalArguments.s

# target to generate assembly for a file
LastalArguments.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/LastalArguments.cc.s
.PHONY : LastalArguments.cc.s

LastdbArguments.o: LastdbArguments.cc.o
.PHONY : LastdbArguments.o

# target to build an object file
LastdbArguments.cc.o:
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/LastdbArguments.cc.o
.PHONY : LastdbArguments.cc.o

LastdbArguments.i: LastdbArguments.cc.i
.PHONY : LastdbArguments.i

# target to preprocess a source file
LastdbArguments.cc.i:
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/LastdbArguments.cc.i
.PHONY : LastdbArguments.cc.i

LastdbArguments.s: LastdbArguments.cc.s
.PHONY : LastdbArguments.s

# target to generate assembly for a file
LastdbArguments.cc.s:
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/LastdbArguments.cc.s
.PHONY : LastdbArguments.cc.s

LastexArguments.o: LastexArguments.cc.o
.PHONY : LastexArguments.o

# target to build an object file
LastexArguments.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/LastexArguments.cc.o
.PHONY : LastexArguments.cc.o

LastexArguments.i: LastexArguments.cc.i
.PHONY : LastexArguments.i

# target to preprocess a source file
LastexArguments.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/LastexArguments.cc.i
.PHONY : LastexArguments.cc.i

LastexArguments.s: LastexArguments.cc.s
.PHONY : LastexArguments.s

# target to generate assembly for a file
LastexArguments.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/LastexArguments.cc.s
.PHONY : LastexArguments.cc.s

MultiSequence.o: MultiSequence.cc.o
.PHONY : MultiSequence.o

# target to build an object file
MultiSequence.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/MultiSequence.cc.o
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/MultiSequence.cc.o
.PHONY : MultiSequence.cc.o

MultiSequence.i: MultiSequence.cc.i
.PHONY : MultiSequence.i

# target to preprocess a source file
MultiSequence.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/MultiSequence.cc.i
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/MultiSequence.cc.i
.PHONY : MultiSequence.cc.i

MultiSequence.s: MultiSequence.cc.s
.PHONY : MultiSequence.s

# target to generate assembly for a file
MultiSequence.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/MultiSequence.cc.s
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/MultiSequence.cc.s
.PHONY : MultiSequence.cc.s

MultiSequenceQual.o: MultiSequenceQual.cc.o
.PHONY : MultiSequenceQual.o

# target to build an object file
MultiSequenceQual.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/MultiSequenceQual.cc.o
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/MultiSequenceQual.cc.o
.PHONY : MultiSequenceQual.cc.o

MultiSequenceQual.i: MultiSequenceQual.cc.i
.PHONY : MultiSequenceQual.i

# target to preprocess a source file
MultiSequenceQual.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/MultiSequenceQual.cc.i
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/MultiSequenceQual.cc.i
.PHONY : MultiSequenceQual.cc.i

MultiSequenceQual.s: MultiSequenceQual.cc.s
.PHONY : MultiSequenceQual.s

# target to generate assembly for a file
MultiSequenceQual.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/MultiSequenceQual.cc.s
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/MultiSequenceQual.cc.s
.PHONY : MultiSequenceQual.cc.s

MultiSequenceUser.o: MultiSequenceUser.cc.o
.PHONY : MultiSequenceUser.o

# target to build an object file
MultiSequenceUser.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/MultiSequenceUser.cc.o
.PHONY : MultiSequenceUser.cc.o

MultiSequenceUser.i: MultiSequenceUser.cc.i
.PHONY : MultiSequenceUser.i

# target to preprocess a source file
MultiSequenceUser.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/MultiSequenceUser.cc.i
.PHONY : MultiSequenceUser.cc.i

MultiSequenceUser.s: MultiSequenceUser.cc.s
.PHONY : MultiSequenceUser.s

# target to generate assembly for a file
MultiSequenceUser.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/MultiSequenceUser.cc.s
.PHONY : MultiSequenceUser.cc.s

OneQualityScoreMatrix.o: OneQualityScoreMatrix.cc.o
.PHONY : OneQualityScoreMatrix.o

# target to build an object file
OneQualityScoreMatrix.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/OneQualityScoreMatrix.cc.o
.PHONY : OneQualityScoreMatrix.cc.o

OneQualityScoreMatrix.i: OneQualityScoreMatrix.cc.i
.PHONY : OneQualityScoreMatrix.i

# target to preprocess a source file
OneQualityScoreMatrix.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/OneQualityScoreMatrix.cc.i
.PHONY : OneQualityScoreMatrix.cc.i

OneQualityScoreMatrix.s: OneQualityScoreMatrix.cc.s
.PHONY : OneQualityScoreMatrix.s

# target to generate assembly for a file
OneQualityScoreMatrix.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/OneQualityScoreMatrix.cc.s
.PHONY : OneQualityScoreMatrix.cc.s

QualityPssmMaker.o: QualityPssmMaker.cc.o
.PHONY : QualityPssmMaker.o

# target to build an object file
QualityPssmMaker.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/QualityPssmMaker.cc.o
.PHONY : QualityPssmMaker.cc.o

QualityPssmMaker.i: QualityPssmMaker.cc.i
.PHONY : QualityPssmMaker.i

# target to preprocess a source file
QualityPssmMaker.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/QualityPssmMaker.cc.i
.PHONY : QualityPssmMaker.cc.i

QualityPssmMaker.s: QualityPssmMaker.cc.s
.PHONY : QualityPssmMaker.s

# target to generate assembly for a file
QualityPssmMaker.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/QualityPssmMaker.cc.s
.PHONY : QualityPssmMaker.cc.s

ScoreMatrix.o: ScoreMatrix.cc.o
.PHONY : ScoreMatrix.o

# target to build an object file
ScoreMatrix.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/ScoreMatrix.cc.o
.PHONY : ScoreMatrix.cc.o

ScoreMatrix.i: ScoreMatrix.cc.i
.PHONY : ScoreMatrix.i

# target to preprocess a source file
ScoreMatrix.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/ScoreMatrix.cc.i
.PHONY : ScoreMatrix.cc.i

ScoreMatrix.s: ScoreMatrix.cc.s
.PHONY : ScoreMatrix.s

# target to generate assembly for a file
ScoreMatrix.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/ScoreMatrix.cc.s
.PHONY : ScoreMatrix.cc.s

SegmentPair.o: SegmentPair.cc.o
.PHONY : SegmentPair.o

# target to build an object file
SegmentPair.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/SegmentPair.cc.o
.PHONY : SegmentPair.cc.o

SegmentPair.i: SegmentPair.cc.i
.PHONY : SegmentPair.i

# target to preprocess a source file
SegmentPair.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/SegmentPair.cc.i
.PHONY : SegmentPair.cc.i

SegmentPair.s: SegmentPair.cc.s
.PHONY : SegmentPair.s

# target to generate assembly for a file
SegmentPair.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/SegmentPair.cc.s
.PHONY : SegmentPair.cc.s

SegmentPairPot.o: SegmentPairPot.cc.o
.PHONY : SegmentPairPot.o

# target to build an object file
SegmentPairPot.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/SegmentPairPot.cc.o
.PHONY : SegmentPairPot.cc.o

SegmentPairPot.i: SegmentPairPot.cc.i
.PHONY : SegmentPairPot.i

# target to preprocess a source file
SegmentPairPot.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/SegmentPairPot.cc.i
.PHONY : SegmentPairPot.cc.i

SegmentPairPot.s: SegmentPairPot.cc.s
.PHONY : SegmentPairPot.s

# target to generate assembly for a file
SegmentPairPot.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/SegmentPairPot.cc.s
.PHONY : SegmentPairPot.cc.s

SubsetSuffixArray.o: SubsetSuffixArray.cc.o
.PHONY : SubsetSuffixArray.o

# target to build an object file
SubsetSuffixArray.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/SubsetSuffixArray.cc.o
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/SubsetSuffixArray.cc.o
.PHONY : SubsetSuffixArray.cc.o

SubsetSuffixArray.i: SubsetSuffixArray.cc.i
.PHONY : SubsetSuffixArray.i

# target to preprocess a source file
SubsetSuffixArray.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/SubsetSuffixArray.cc.i
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/SubsetSuffixArray.cc.i
.PHONY : SubsetSuffixArray.cc.i

SubsetSuffixArray.s: SubsetSuffixArray.cc.s
.PHONY : SubsetSuffixArray.s

# target to generate assembly for a file
SubsetSuffixArray.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/SubsetSuffixArray.cc.s
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/SubsetSuffixArray.cc.s
.PHONY : SubsetSuffixArray.cc.s

SubsetSuffixArraySort.o: SubsetSuffixArraySort.cc.o
.PHONY : SubsetSuffixArraySort.o

# target to build an object file
SubsetSuffixArraySort.cc.o:
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/SubsetSuffixArraySort.cc.o
.PHONY : SubsetSuffixArraySort.cc.o

SubsetSuffixArraySort.i: SubsetSuffixArraySort.cc.i
.PHONY : SubsetSuffixArraySort.i

# target to preprocess a source file
SubsetSuffixArraySort.cc.i:
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/SubsetSuffixArraySort.cc.i
.PHONY : SubsetSuffixArraySort.cc.i

SubsetSuffixArraySort.s: SubsetSuffixArraySort.cc.s
.PHONY : SubsetSuffixArraySort.s

# target to generate assembly for a file
SubsetSuffixArraySort.cc.s:
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/SubsetSuffixArraySort.cc.s
.PHONY : SubsetSuffixArraySort.cc.s

SubsetSuffixArrayUser.o: SubsetSuffixArrayUser.cc.o
.PHONY : SubsetSuffixArrayUser.o

# target to build an object file
SubsetSuffixArrayUser.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/SubsetSuffixArrayUser.cc.o
.PHONY : SubsetSuffixArrayUser.cc.o

SubsetSuffixArrayUser.i: SubsetSuffixArrayUser.cc.i
.PHONY : SubsetSuffixArrayUser.i

# target to preprocess a source file
SubsetSuffixArrayUser.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/SubsetSuffixArrayUser.cc.i
.PHONY : SubsetSuffixArrayUser.cc.i

SubsetSuffixArrayUser.s: SubsetSuffixArrayUser.cc.s
.PHONY : SubsetSuffixArrayUser.s

# target to generate assembly for a file
SubsetSuffixArrayUser.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/SubsetSuffixArrayUser.cc.s
.PHONY : SubsetSuffixArrayUser.cc.s

TwoQualityScoreMatrix.o: TwoQualityScoreMatrix.cc.o
.PHONY : TwoQualityScoreMatrix.o

# target to build an object file
TwoQualityScoreMatrix.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/TwoQualityScoreMatrix.cc.o
.PHONY : TwoQualityScoreMatrix.cc.o

TwoQualityScoreMatrix.i: TwoQualityScoreMatrix.cc.i
.PHONY : TwoQualityScoreMatrix.i

# target to preprocess a source file
TwoQualityScoreMatrix.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/TwoQualityScoreMatrix.cc.i
.PHONY : TwoQualityScoreMatrix.cc.i

TwoQualityScoreMatrix.s: TwoQualityScoreMatrix.cc.s
.PHONY : TwoQualityScoreMatrix.s

# target to generate assembly for a file
TwoQualityScoreMatrix.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/TwoQualityScoreMatrix.cc.s
.PHONY : TwoQualityScoreMatrix.cc.s

fileMap.o: fileMap.cc.o
.PHONY : fileMap.o

# target to build an object file
fileMap.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/fileMap.cc.o
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/fileMap.cc.o
.PHONY : fileMap.cc.o

fileMap.i: fileMap.cc.i
.PHONY : fileMap.i

# target to preprocess a source file
fileMap.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/fileMap.cc.i
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/fileMap.cc.i
.PHONY : fileMap.cc.i

fileMap.s: fileMap.cc.s
.PHONY : fileMap.s

# target to generate assembly for a file
fileMap.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/fileMap.cc.s
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/fileMap.cc.s
.PHONY : fileMap.cc.s

gaplessPssmXdrop.o: gaplessPssmXdrop.cc.o
.PHONY : gaplessPssmXdrop.o

# target to build an object file
gaplessPssmXdrop.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gaplessPssmXdrop.cc.o
.PHONY : gaplessPssmXdrop.cc.o

gaplessPssmXdrop.i: gaplessPssmXdrop.cc.i
.PHONY : gaplessPssmXdrop.i

# target to preprocess a source file
gaplessPssmXdrop.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gaplessPssmXdrop.cc.i
.PHONY : gaplessPssmXdrop.cc.i

gaplessPssmXdrop.s: gaplessPssmXdrop.cc.s
.PHONY : gaplessPssmXdrop.s

# target to generate assembly for a file
gaplessPssmXdrop.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gaplessPssmXdrop.cc.s
.PHONY : gaplessPssmXdrop.cc.s

gaplessTwoQualityXdrop.o: gaplessTwoQualityXdrop.cc.o
.PHONY : gaplessTwoQualityXdrop.o

# target to build an object file
gaplessTwoQualityXdrop.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gaplessTwoQualityXdrop.cc.o
.PHONY : gaplessTwoQualityXdrop.cc.o

gaplessTwoQualityXdrop.i: gaplessTwoQualityXdrop.cc.i
.PHONY : gaplessTwoQualityXdrop.i

# target to preprocess a source file
gaplessTwoQualityXdrop.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gaplessTwoQualityXdrop.cc.i
.PHONY : gaplessTwoQualityXdrop.cc.i

gaplessTwoQualityXdrop.s: gaplessTwoQualityXdrop.cc.s
.PHONY : gaplessTwoQualityXdrop.s

# target to generate assembly for a file
gaplessTwoQualityXdrop.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gaplessTwoQualityXdrop.cc.s
.PHONY : gaplessTwoQualityXdrop.cc.s

gaplessXdrop.o: gaplessXdrop.cc.o
.PHONY : gaplessXdrop.o

# target to build an object file
gaplessXdrop.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gaplessXdrop.cc.o
.PHONY : gaplessXdrop.cc.o

gaplessXdrop.i: gaplessXdrop.cc.i
.PHONY : gaplessXdrop.i

# target to preprocess a source file
gaplessXdrop.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gaplessXdrop.cc.i
.PHONY : gaplessXdrop.cc.i

gaplessXdrop.s: gaplessXdrop.cc.s
.PHONY : gaplessXdrop.s

# target to generate assembly for a file
gaplessXdrop.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gaplessXdrop.cc.s
.PHONY : gaplessXdrop.cc.s

gumbel_params/mcf_local_alignment_evaluer.o: gumbel_params/mcf_local_alignment_evaluer.cpp.o
.PHONY : gumbel_params/mcf_local_alignment_evaluer.o

# target to build an object file
gumbel_params/mcf_local_alignment_evaluer.cpp.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/mcf_local_alignment_evaluer.cpp.o
.PHONY : gumbel_params/mcf_local_alignment_evaluer.cpp.o

gumbel_params/mcf_local_alignment_evaluer.i: gumbel_params/mcf_local_alignment_evaluer.cpp.i
.PHONY : gumbel_params/mcf_local_alignment_evaluer.i

# target to preprocess a source file
gumbel_params/mcf_local_alignment_evaluer.cpp.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/mcf_local_alignment_evaluer.cpp.i
.PHONY : gumbel_params/mcf_local_alignment_evaluer.cpp.i

gumbel_params/mcf_local_alignment_evaluer.s: gumbel_params/mcf_local_alignment_evaluer.cpp.s
.PHONY : gumbel_params/mcf_local_alignment_evaluer.s

# target to generate assembly for a file
gumbel_params/mcf_local_alignment_evaluer.cpp.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/mcf_local_alignment_evaluer.cpp.s
.PHONY : gumbel_params/mcf_local_alignment_evaluer.cpp.s

gumbel_params/njn_dynprogprob.o: gumbel_params/njn_dynprogprob.cpp.o
.PHONY : gumbel_params/njn_dynprogprob.o

# target to build an object file
gumbel_params/njn_dynprogprob.cpp.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/njn_dynprogprob.cpp.o
.PHONY : gumbel_params/njn_dynprogprob.cpp.o

gumbel_params/njn_dynprogprob.i: gumbel_params/njn_dynprogprob.cpp.i
.PHONY : gumbel_params/njn_dynprogprob.i

# target to preprocess a source file
gumbel_params/njn_dynprogprob.cpp.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/njn_dynprogprob.cpp.i
.PHONY : gumbel_params/njn_dynprogprob.cpp.i

gumbel_params/njn_dynprogprob.s: gumbel_params/njn_dynprogprob.cpp.s
.PHONY : gumbel_params/njn_dynprogprob.s

# target to generate assembly for a file
gumbel_params/njn_dynprogprob.cpp.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/njn_dynprogprob.cpp.s
.PHONY : gumbel_params/njn_dynprogprob.cpp.s

gumbel_params/njn_dynprogproblim.o: gumbel_params/njn_dynprogproblim.cpp.o
.PHONY : gumbel_params/njn_dynprogproblim.o

# target to build an object file
gumbel_params/njn_dynprogproblim.cpp.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/njn_dynprogproblim.cpp.o
.PHONY : gumbel_params/njn_dynprogproblim.cpp.o

gumbel_params/njn_dynprogproblim.i: gumbel_params/njn_dynprogproblim.cpp.i
.PHONY : gumbel_params/njn_dynprogproblim.i

# target to preprocess a source file
gumbel_params/njn_dynprogproblim.cpp.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/njn_dynprogproblim.cpp.i
.PHONY : gumbel_params/njn_dynprogproblim.cpp.i

gumbel_params/njn_dynprogproblim.s: gumbel_params/njn_dynprogproblim.cpp.s
.PHONY : gumbel_params/njn_dynprogproblim.s

# target to generate assembly for a file
gumbel_params/njn_dynprogproblim.cpp.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/njn_dynprogproblim.cpp.s
.PHONY : gumbel_params/njn_dynprogproblim.cpp.s

gumbel_params/njn_dynprogprobproto.o: gumbel_params/njn_dynprogprobproto.cpp.o
.PHONY : gumbel_params/njn_dynprogprobproto.o

# target to build an object file
gumbel_params/njn_dynprogprobproto.cpp.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/njn_dynprogprobproto.cpp.o
.PHONY : gumbel_params/njn_dynprogprobproto.cpp.o

gumbel_params/njn_dynprogprobproto.i: gumbel_params/njn_dynprogprobproto.cpp.i
.PHONY : gumbel_params/njn_dynprogprobproto.i

# target to preprocess a source file
gumbel_params/njn_dynprogprobproto.cpp.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/njn_dynprogprobproto.cpp.i
.PHONY : gumbel_params/njn_dynprogprobproto.cpp.i

gumbel_params/njn_dynprogprobproto.s: gumbel_params/njn_dynprogprobproto.cpp.s
.PHONY : gumbel_params/njn_dynprogprobproto.s

# target to generate assembly for a file
gumbel_params/njn_dynprogprobproto.cpp.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/njn_dynprogprobproto.cpp.s
.PHONY : gumbel_params/njn_dynprogprobproto.cpp.s

gumbel_params/njn_ioutil.o: gumbel_params/njn_ioutil.cpp.o
.PHONY : gumbel_params/njn_ioutil.o

# target to build an object file
gumbel_params/njn_ioutil.cpp.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/njn_ioutil.cpp.o
.PHONY : gumbel_params/njn_ioutil.cpp.o

gumbel_params/njn_ioutil.i: gumbel_params/njn_ioutil.cpp.i
.PHONY : gumbel_params/njn_ioutil.i

# target to preprocess a source file
gumbel_params/njn_ioutil.cpp.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/njn_ioutil.cpp.i
.PHONY : gumbel_params/njn_ioutil.cpp.i

gumbel_params/njn_ioutil.s: gumbel_params/njn_ioutil.cpp.s
.PHONY : gumbel_params/njn_ioutil.s

# target to generate assembly for a file
gumbel_params/njn_ioutil.cpp.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/njn_ioutil.cpp.s
.PHONY : gumbel_params/njn_ioutil.cpp.s

gumbel_params/njn_localmaxstat.o: gumbel_params/njn_localmaxstat.cpp.o
.PHONY : gumbel_params/njn_localmaxstat.o

# target to build an object file
gumbel_params/njn_localmaxstat.cpp.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/njn_localmaxstat.cpp.o
.PHONY : gumbel_params/njn_localmaxstat.cpp.o

gumbel_params/njn_localmaxstat.i: gumbel_params/njn_localmaxstat.cpp.i
.PHONY : gumbel_params/njn_localmaxstat.i

# target to preprocess a source file
gumbel_params/njn_localmaxstat.cpp.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/njn_localmaxstat.cpp.i
.PHONY : gumbel_params/njn_localmaxstat.cpp.i

gumbel_params/njn_localmaxstat.s: gumbel_params/njn_localmaxstat.cpp.s
.PHONY : gumbel_params/njn_localmaxstat.s

# target to generate assembly for a file
gumbel_params/njn_localmaxstat.cpp.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/njn_localmaxstat.cpp.s
.PHONY : gumbel_params/njn_localmaxstat.cpp.s

gumbel_params/njn_localmaxstatmatrix.o: gumbel_params/njn_localmaxstatmatrix.cpp.o
.PHONY : gumbel_params/njn_localmaxstatmatrix.o

# target to build an object file
gumbel_params/njn_localmaxstatmatrix.cpp.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/njn_localmaxstatmatrix.cpp.o
.PHONY : gumbel_params/njn_localmaxstatmatrix.cpp.o

gumbel_params/njn_localmaxstatmatrix.i: gumbel_params/njn_localmaxstatmatrix.cpp.i
.PHONY : gumbel_params/njn_localmaxstatmatrix.i

# target to preprocess a source file
gumbel_params/njn_localmaxstatmatrix.cpp.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/njn_localmaxstatmatrix.cpp.i
.PHONY : gumbel_params/njn_localmaxstatmatrix.cpp.i

gumbel_params/njn_localmaxstatmatrix.s: gumbel_params/njn_localmaxstatmatrix.cpp.s
.PHONY : gumbel_params/njn_localmaxstatmatrix.s

# target to generate assembly for a file
gumbel_params/njn_localmaxstatmatrix.cpp.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/njn_localmaxstatmatrix.cpp.s
.PHONY : gumbel_params/njn_localmaxstatmatrix.cpp.s

gumbel_params/njn_localmaxstatutil.o: gumbel_params/njn_localmaxstatutil.cpp.o
.PHONY : gumbel_params/njn_localmaxstatutil.o

# target to build an object file
gumbel_params/njn_localmaxstatutil.cpp.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/njn_localmaxstatutil.cpp.o
.PHONY : gumbel_params/njn_localmaxstatutil.cpp.o

gumbel_params/njn_localmaxstatutil.i: gumbel_params/njn_localmaxstatutil.cpp.i
.PHONY : gumbel_params/njn_localmaxstatutil.i

# target to preprocess a source file
gumbel_params/njn_localmaxstatutil.cpp.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/njn_localmaxstatutil.cpp.i
.PHONY : gumbel_params/njn_localmaxstatutil.cpp.i

gumbel_params/njn_localmaxstatutil.s: gumbel_params/njn_localmaxstatutil.cpp.s
.PHONY : gumbel_params/njn_localmaxstatutil.s

# target to generate assembly for a file
gumbel_params/njn_localmaxstatutil.cpp.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/njn_localmaxstatutil.cpp.s
.PHONY : gumbel_params/njn_localmaxstatutil.cpp.s

gumbel_params/njn_matrix.o: gumbel_params/njn_matrix.cpp.o
.PHONY : gumbel_params/njn_matrix.o

# target to build an object file
gumbel_params/njn_matrix.cpp.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/njn_matrix.cpp.o
.PHONY : gumbel_params/njn_matrix.cpp.o

gumbel_params/njn_matrix.i: gumbel_params/njn_matrix.cpp.i
.PHONY : gumbel_params/njn_matrix.i

# target to preprocess a source file
gumbel_params/njn_matrix.cpp.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/njn_matrix.cpp.i
.PHONY : gumbel_params/njn_matrix.cpp.i

gumbel_params/njn_matrix.s: gumbel_params/njn_matrix.cpp.s
.PHONY : gumbel_params/njn_matrix.s

# target to generate assembly for a file
gumbel_params/njn_matrix.cpp.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/njn_matrix.cpp.s
.PHONY : gumbel_params/njn_matrix.cpp.s

gumbel_params/random_gen.o: gumbel_params/random_gen.cpp.o
.PHONY : gumbel_params/random_gen.o

# target to build an object file
gumbel_params/random_gen.cpp.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/random_gen.cpp.o
.PHONY : gumbel_params/random_gen.cpp.o

gumbel_params/random_gen.i: gumbel_params/random_gen.cpp.i
.PHONY : gumbel_params/random_gen.i

# target to preprocess a source file
gumbel_params/random_gen.cpp.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/random_gen.cpp.i
.PHONY : gumbel_params/random_gen.cpp.i

gumbel_params/random_gen.s: gumbel_params/random_gen.cpp.s
.PHONY : gumbel_params/random_gen.s

# target to generate assembly for a file
gumbel_params/random_gen.cpp.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/random_gen.cpp.s
.PHONY : gumbel_params/random_gen.cpp.s

gumbel_params/sls_alp.o: gumbel_params/sls_alp.cpp.o
.PHONY : gumbel_params/sls_alp.o

# target to build an object file
gumbel_params/sls_alp.cpp.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/sls_alp.cpp.o
.PHONY : gumbel_params/sls_alp.cpp.o

gumbel_params/sls_alp.i: gumbel_params/sls_alp.cpp.i
.PHONY : gumbel_params/sls_alp.i

# target to preprocess a source file
gumbel_params/sls_alp.cpp.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/sls_alp.cpp.i
.PHONY : gumbel_params/sls_alp.cpp.i

gumbel_params/sls_alp.s: gumbel_params/sls_alp.cpp.s
.PHONY : gumbel_params/sls_alp.s

# target to generate assembly for a file
gumbel_params/sls_alp.cpp.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/sls_alp.cpp.s
.PHONY : gumbel_params/sls_alp.cpp.s

gumbel_params/sls_alp_data.o: gumbel_params/sls_alp_data.cpp.o
.PHONY : gumbel_params/sls_alp_data.o

# target to build an object file
gumbel_params/sls_alp_data.cpp.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/sls_alp_data.cpp.o
.PHONY : gumbel_params/sls_alp_data.cpp.o

gumbel_params/sls_alp_data.i: gumbel_params/sls_alp_data.cpp.i
.PHONY : gumbel_params/sls_alp_data.i

# target to preprocess a source file
gumbel_params/sls_alp_data.cpp.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/sls_alp_data.cpp.i
.PHONY : gumbel_params/sls_alp_data.cpp.i

gumbel_params/sls_alp_data.s: gumbel_params/sls_alp_data.cpp.s
.PHONY : gumbel_params/sls_alp_data.s

# target to generate assembly for a file
gumbel_params/sls_alp_data.cpp.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/sls_alp_data.cpp.s
.PHONY : gumbel_params/sls_alp_data.cpp.s

gumbel_params/sls_alp_regression.o: gumbel_params/sls_alp_regression.cpp.o
.PHONY : gumbel_params/sls_alp_regression.o

# target to build an object file
gumbel_params/sls_alp_regression.cpp.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/sls_alp_regression.cpp.o
.PHONY : gumbel_params/sls_alp_regression.cpp.o

gumbel_params/sls_alp_regression.i: gumbel_params/sls_alp_regression.cpp.i
.PHONY : gumbel_params/sls_alp_regression.i

# target to preprocess a source file
gumbel_params/sls_alp_regression.cpp.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/sls_alp_regression.cpp.i
.PHONY : gumbel_params/sls_alp_regression.cpp.i

gumbel_params/sls_alp_regression.s: gumbel_params/sls_alp_regression.cpp.s
.PHONY : gumbel_params/sls_alp_regression.s

# target to generate assembly for a file
gumbel_params/sls_alp_regression.cpp.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/sls_alp_regression.cpp.s
.PHONY : gumbel_params/sls_alp_regression.cpp.s

gumbel_params/sls_alp_sim.o: gumbel_params/sls_alp_sim.cpp.o
.PHONY : gumbel_params/sls_alp_sim.o

# target to build an object file
gumbel_params/sls_alp_sim.cpp.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/sls_alp_sim.cpp.o
.PHONY : gumbel_params/sls_alp_sim.cpp.o

gumbel_params/sls_alp_sim.i: gumbel_params/sls_alp_sim.cpp.i
.PHONY : gumbel_params/sls_alp_sim.i

# target to preprocess a source file
gumbel_params/sls_alp_sim.cpp.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/sls_alp_sim.cpp.i
.PHONY : gumbel_params/sls_alp_sim.cpp.i

gumbel_params/sls_alp_sim.s: gumbel_params/sls_alp_sim.cpp.s
.PHONY : gumbel_params/sls_alp_sim.s

# target to generate assembly for a file
gumbel_params/sls_alp_sim.cpp.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/sls_alp_sim.cpp.s
.PHONY : gumbel_params/sls_alp_sim.cpp.s

gumbel_params/sls_pvalues.o: gumbel_params/sls_pvalues.cpp.o
.PHONY : gumbel_params/sls_pvalues.o

# target to build an object file
gumbel_params/sls_pvalues.cpp.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/sls_pvalues.cpp.o
.PHONY : gumbel_params/sls_pvalues.cpp.o

gumbel_params/sls_pvalues.i: gumbel_params/sls_pvalues.cpp.i
.PHONY : gumbel_params/sls_pvalues.i

# target to preprocess a source file
gumbel_params/sls_pvalues.cpp.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/sls_pvalues.cpp.i
.PHONY : gumbel_params/sls_pvalues.cpp.i

gumbel_params/sls_pvalues.s: gumbel_params/sls_pvalues.cpp.s
.PHONY : gumbel_params/sls_pvalues.s

# target to generate assembly for a file
gumbel_params/sls_pvalues.cpp.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/gumbel_params/sls_pvalues.cpp.s
.PHONY : gumbel_params/sls_pvalues.cpp.s

io.o: io.cc.o
.PHONY : io.o

# target to build an object file
io.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/io.cc.o
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/io.cc.o
.PHONY : io.cc.o

io.i: io.cc.i
.PHONY : io.i

# target to preprocess a source file
io.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/io.cc.i
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/io.cc.i
.PHONY : io.cc.i

io.s: io.cc.s
.PHONY : io.s

# target to generate assembly for a file
io.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/io.cc.s
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/io.cc.s
.PHONY : io.cc.s

lambda_calculator.o: lambda_calculator.cc.o
.PHONY : lambda_calculator.o

# target to build an object file
lambda_calculator.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/lambda_calculator.cc.o
.PHONY : lambda_calculator.cc.o

lambda_calculator.i: lambda_calculator.cc.i
.PHONY : lambda_calculator.i

# target to preprocess a source file
lambda_calculator.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/lambda_calculator.cc.i
.PHONY : lambda_calculator.cc.i

lambda_calculator.s: lambda_calculator.cc.s
.PHONY : lambda_calculator.s

# target to generate assembly for a file
lambda_calculator.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/lambda_calculator.cc.s
.PHONY : lambda_calculator.cc.s

lastal.o: lastal.cc.o
.PHONY : lastal.o

# target to build an object file
lastal.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/lastal.cc.o
.PHONY : lastal.cc.o

lastal.i: lastal.cc.i
.PHONY : lastal.i

# target to preprocess a source file
lastal.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/lastal.cc.i
.PHONY : lastal.cc.i

lastal.s: lastal.cc.s
.PHONY : lastal.s

# target to generate assembly for a file
lastal.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/lastal.cc.s
.PHONY : lastal.cc.s

lastdb.o: lastdb.cc.o
.PHONY : lastdb.o

# target to build an object file
lastdb.cc.o:
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/lastdb.cc.o
.PHONY : lastdb.cc.o

lastdb.i: lastdb.cc.i
.PHONY : lastdb.i

# target to preprocess a source file
lastdb.cc.i:
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/lastdb.cc.i
.PHONY : lastdb.cc.i

lastdb.s: lastdb.cc.s
.PHONY : lastdb.s

# target to generate assembly for a file
lastdb.cc.s:
	$(MAKE) -f CMakeFiles/lastdb.dir/build.make CMakeFiles/lastdb.dir/lastdb.cc.s
.PHONY : lastdb.cc.s

lastex.o: lastex.cc.o
.PHONY : lastex.o

# target to build an object file
lastex.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/lastex.cc.o
.PHONY : lastex.cc.o

lastex.i: lastex.cc.i
.PHONY : lastex.i

# target to preprocess a source file
lastex.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/lastex.cc.i
.PHONY : lastex.cc.i

lastex.s: lastex.cc.s
.PHONY : lastex.s

# target to generate assembly for a file
lastex.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/lastex.cc.s
.PHONY : lastex.cc.s

lubksb.o: lubksb.cc.o
.PHONY : lubksb.o

# target to build an object file
lubksb.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/lubksb.cc.o
.PHONY : lubksb.cc.o

lubksb.i: lubksb.cc.i
.PHONY : lubksb.i

# target to preprocess a source file
lubksb.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/lubksb.cc.i
.PHONY : lubksb.cc.i

lubksb.s: lubksb.cc.s
.PHONY : lubksb.s

# target to generate assembly for a file
lubksb.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/lubksb.cc.s
.PHONY : lubksb.cc.s

ludcmp.o: ludcmp.cc.o
.PHONY : ludcmp.o

# target to build an object file
ludcmp.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/ludcmp.cc.o
.PHONY : ludcmp.cc.o

ludcmp.i: ludcmp.cc.i
.PHONY : ludcmp.i

# target to preprocess a source file
ludcmp.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/ludcmp.cc.i
.PHONY : ludcmp.cc.i

ludcmp.s: ludcmp.cc.s
.PHONY : ludcmp.s

# target to generate assembly for a file
ludcmp.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/ludcmp.cc.s
.PHONY : ludcmp.cc.s

nrutil.o: nrutil.cc.o
.PHONY : nrutil.o

# target to build an object file
nrutil.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/nrutil.cc.o
.PHONY : nrutil.cc.o

nrutil.i: nrutil.cc.i
.PHONY : nrutil.i

# target to preprocess a source file
nrutil.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/nrutil.cc.i
.PHONY : nrutil.cc.i

nrutil.s: nrutil.cc.s
.PHONY : nrutil.s

# target to generate assembly for a file
nrutil.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/nrutil.cc.s
.PHONY : nrutil.cc.s

utils.o: utils.cc.o
.PHONY : utils.o

# target to build an object file
utils.cc.o:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/utils.cc.o
.PHONY : utils.cc.o

utils.i: utils.cc.i
.PHONY : utils.i

# target to preprocess a source file
utils.cc.i:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/utils.cc.i
.PHONY : utils.cc.i

utils.s: utils.cc.s
.PHONY : utils.s

# target to generate assembly for a file
utils.cc.s:
	$(MAKE) -f CMakeFiles/lastal.dir/build.make CMakeFiles/lastal.dir/utils.cc.s
.PHONY : utils.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lastal"
	@echo "... lastdb"
	@echo "... Alignment.o"
	@echo "... Alignment.i"
	@echo "... Alignment.s"
	@echo "... AlignmentPot.o"
	@echo "... AlignmentPot.i"
	@echo "... AlignmentPot.s"
	@echo "... AlignmentWrite.o"
	@echo "... AlignmentWrite.i"
	@echo "... AlignmentWrite.s"
	@echo "... Alphabet.o"
	@echo "... Alphabet.i"
	@echo "... Alphabet.s"
	@echo "... Centroid.o"
	@echo "... Centroid.i"
	@echo "... Centroid.s"
	@echo "... CyclicSubsetSeed.o"
	@echo "... CyclicSubsetSeed.i"
	@echo "... CyclicSubsetSeed.s"
	@echo "... DiagonalTable.o"
	@echo "... DiagonalTable.i"
	@echo "... DiagonalTable.s"
	@echo "... GappedXdropAligner.o"
	@echo "... GappedXdropAligner.i"
	@echo "... GappedXdropAligner.s"
	@echo "... GappedXdropAligner2qual.o"
	@echo "... GappedXdropAligner2qual.i"
	@echo "... GappedXdropAligner2qual.s"
	@echo "... GappedXdropAligner3frame.o"
	@echo "... GappedXdropAligner3frame.i"
	@echo "... GappedXdropAligner3frame.s"
	@echo "... GappedXdropAlignerPssm.o"
	@echo "... GappedXdropAlignerPssm.i"
	@echo "... GappedXdropAlignerPssm.s"
	@echo "... GeneralizedAffineGapCosts.o"
	@echo "... GeneralizedAffineGapCosts.i"
	@echo "... GeneralizedAffineGapCosts.s"
	@echo "... GeneticCode.o"
	@echo "... GeneticCode.i"
	@echo "... GeneticCode.s"
	@echo "... LambdaCalculator.o"
	@echo "... LambdaCalculator.i"
	@echo "... LambdaCalculator.s"
	@echo "... LastalArguments.o"
	@echo "... LastalArguments.i"
	@echo "... LastalArguments.s"
	@echo "... LastdbArguments.o"
	@echo "... LastdbArguments.i"
	@echo "... LastdbArguments.s"
	@echo "... LastexArguments.o"
	@echo "... LastexArguments.i"
	@echo "... LastexArguments.s"
	@echo "... MultiSequence.o"
	@echo "... MultiSequence.i"
	@echo "... MultiSequence.s"
	@echo "... MultiSequenceQual.o"
	@echo "... MultiSequenceQual.i"
	@echo "... MultiSequenceQual.s"
	@echo "... MultiSequenceUser.o"
	@echo "... MultiSequenceUser.i"
	@echo "... MultiSequenceUser.s"
	@echo "... OneQualityScoreMatrix.o"
	@echo "... OneQualityScoreMatrix.i"
	@echo "... OneQualityScoreMatrix.s"
	@echo "... QualityPssmMaker.o"
	@echo "... QualityPssmMaker.i"
	@echo "... QualityPssmMaker.s"
	@echo "... ScoreMatrix.o"
	@echo "... ScoreMatrix.i"
	@echo "... ScoreMatrix.s"
	@echo "... SegmentPair.o"
	@echo "... SegmentPair.i"
	@echo "... SegmentPair.s"
	@echo "... SegmentPairPot.o"
	@echo "... SegmentPairPot.i"
	@echo "... SegmentPairPot.s"
	@echo "... SubsetSuffixArray.o"
	@echo "... SubsetSuffixArray.i"
	@echo "... SubsetSuffixArray.s"
	@echo "... SubsetSuffixArraySort.o"
	@echo "... SubsetSuffixArraySort.i"
	@echo "... SubsetSuffixArraySort.s"
	@echo "... SubsetSuffixArrayUser.o"
	@echo "... SubsetSuffixArrayUser.i"
	@echo "... SubsetSuffixArrayUser.s"
	@echo "... TwoQualityScoreMatrix.o"
	@echo "... TwoQualityScoreMatrix.i"
	@echo "... TwoQualityScoreMatrix.s"
	@echo "... fileMap.o"
	@echo "... fileMap.i"
	@echo "... fileMap.s"
	@echo "... gaplessPssmXdrop.o"
	@echo "... gaplessPssmXdrop.i"
	@echo "... gaplessPssmXdrop.s"
	@echo "... gaplessTwoQualityXdrop.o"
	@echo "... gaplessTwoQualityXdrop.i"
	@echo "... gaplessTwoQualityXdrop.s"
	@echo "... gaplessXdrop.o"
	@echo "... gaplessXdrop.i"
	@echo "... gaplessXdrop.s"
	@echo "... gumbel_params/mcf_local_alignment_evaluer.o"
	@echo "... gumbel_params/mcf_local_alignment_evaluer.i"
	@echo "... gumbel_params/mcf_local_alignment_evaluer.s"
	@echo "... gumbel_params/njn_dynprogprob.o"
	@echo "... gumbel_params/njn_dynprogprob.i"
	@echo "... gumbel_params/njn_dynprogprob.s"
	@echo "... gumbel_params/njn_dynprogproblim.o"
	@echo "... gumbel_params/njn_dynprogproblim.i"
	@echo "... gumbel_params/njn_dynprogproblim.s"
	@echo "... gumbel_params/njn_dynprogprobproto.o"
	@echo "... gumbel_params/njn_dynprogprobproto.i"
	@echo "... gumbel_params/njn_dynprogprobproto.s"
	@echo "... gumbel_params/njn_ioutil.o"
	@echo "... gumbel_params/njn_ioutil.i"
	@echo "... gumbel_params/njn_ioutil.s"
	@echo "... gumbel_params/njn_localmaxstat.o"
	@echo "... gumbel_params/njn_localmaxstat.i"
	@echo "... gumbel_params/njn_localmaxstat.s"
	@echo "... gumbel_params/njn_localmaxstatmatrix.o"
	@echo "... gumbel_params/njn_localmaxstatmatrix.i"
	@echo "... gumbel_params/njn_localmaxstatmatrix.s"
	@echo "... gumbel_params/njn_localmaxstatutil.o"
	@echo "... gumbel_params/njn_localmaxstatutil.i"
	@echo "... gumbel_params/njn_localmaxstatutil.s"
	@echo "... gumbel_params/njn_matrix.o"
	@echo "... gumbel_params/njn_matrix.i"
	@echo "... gumbel_params/njn_matrix.s"
	@echo "... gumbel_params/random_gen.o"
	@echo "... gumbel_params/random_gen.i"
	@echo "... gumbel_params/random_gen.s"
	@echo "... gumbel_params/sls_alp.o"
	@echo "... gumbel_params/sls_alp.i"
	@echo "... gumbel_params/sls_alp.s"
	@echo "... gumbel_params/sls_alp_data.o"
	@echo "... gumbel_params/sls_alp_data.i"
	@echo "... gumbel_params/sls_alp_data.s"
	@echo "... gumbel_params/sls_alp_regression.o"
	@echo "... gumbel_params/sls_alp_regression.i"
	@echo "... gumbel_params/sls_alp_regression.s"
	@echo "... gumbel_params/sls_alp_sim.o"
	@echo "... gumbel_params/sls_alp_sim.i"
	@echo "... gumbel_params/sls_alp_sim.s"
	@echo "... gumbel_params/sls_pvalues.o"
	@echo "... gumbel_params/sls_pvalues.i"
	@echo "... gumbel_params/sls_pvalues.s"
	@echo "... io.o"
	@echo "... io.i"
	@echo "... io.s"
	@echo "... lambda_calculator.o"
	@echo "... lambda_calculator.i"
	@echo "... lambda_calculator.s"
	@echo "... lastal.o"
	@echo "... lastal.i"
	@echo "... lastal.s"
	@echo "... lastdb.o"
	@echo "... lastdb.i"
	@echo "... lastdb.s"
	@echo "... lastex.o"
	@echo "... lastex.i"
	@echo "... lastex.s"
	@echo "... lubksb.o"
	@echo "... lubksb.i"
	@echo "... lubksb.s"
	@echo "... ludcmp.o"
	@echo "... ludcmp.i"
	@echo "... ludcmp.s"
	@echo "... nrutil.o"
	@echo "... nrutil.i"
	@echo "... nrutil.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

